### ISSUE TITLE
Requires `unzip`

### ISSUE THREAD

**Issue by mxcl** [denoland/setup-deno#41]
When running in minimal containers the action fails due to a lack of `unzip`, eg:

https://github.com/teaxyz/cli/actions/runs/4105361554/jobs/7082110062#step:4:8

You may feel this is “working as designed” in which case I’ll submit a PR for the README. Or perhaps you think this action should work even if `unzip` is not available—in which case perhaps there is a package npm or otherwise that will uncompress for us?

**Comment by kt3k** [comment]
We use `@actions/tool-cache` for extracting zip and it depends on `unzip` in PATH. (They seem to have moved to system's `unzip` intentionally https://github.com/actions/toolkit/blob/main/packages/tool-cache/RELEASES.md#112)

I think this is by design.

cc @bartlomieju @satyarohith What do you think?

**Comment by bartlomieju** [comment]
I think it's reasonable if that's the default behavior of the GH's Actions toolkit.

**Comment by lucacasonato** [comment]
Yeah, this is expected behaviour.
